# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT

[default.extend-words]
abd = "abd"
alo = "alo"
beizer = "beizer"
cleary = "cleary"
dingee = "dingee"
lamba = "lamba"
lok = "lok"
namin = "namin"
ond = "ond"
packt = "packt"
sherif = "sherif"
tung = "tung"
tunnell = "tunnell"
